Capturing in make/cc mode...
/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/_warnings-8f2147.o: In function `PyErr_WarnFormat':
_warnings.c:(.text+0x155): undefined reference to `PyUnicode_FromFormatV'
/tmp/_warnings-8f2147.o: In function `warn_unicode':
_warnings.c:(.text+0x203): undefined reference to `PyExc_RuntimeWarning'
/tmp/_warnings-8f2147.o: In function `PyErr_WarnEx':
_warnings.c:(.text+0x2a9): undefined reference to `PyUnicode_FromString'
/tmp/_warnings-8f2147.o: In function `PyErr_WarnExplicitObject':
_warnings.c:(.text+0x38e): undefined reference to `PyExc_RuntimeWarning'
/tmp/_warnings-8f2147.o: In function `warn_explicit':
_warnings.c:(.text+0x488): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4a2): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4b0): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4b6): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4f3): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x509): undefined reference to `PyExc_TypeError'
_warnings.c:(.text+0x518): undefined reference to `PyErr_SetString'
_warnings.c:(.text+0x588): undefined reference to `PyExc_Warning'
_warnings.c:(.text+0x58d): undefined reference to `PyObject_IsInstance'
_warnings.c:(.text+0x5b2): undefined reference to `PyObject_Str'
_warnings.c:(.text+0x5f8): undefined reference to `PyObject_CallFunction'
_warnings.c:(.text+0x61a): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x646): undefined reference to `PyTuple_Pack'
_warnings.c:(.text+0x66b): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x6f3): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x709): undefined reference to `PyErr_SetObject'
_warnings.c:(.text+0x728): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x742): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x75e): undefined reference to `_Py_TrueStruct'
_warnings.c:(.text+0x767): undefined reference to `PyDict_SetItem'
_warnings.c:(.text+0x788): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x7a9): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x7c3): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x81d): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x837): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x873): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x884): undefined reference to `PyExc_RuntimeError'
_warnings.c:(.text+0x89d): undefined reference to `PyErr_Format'
_warnings.c:(.text+0x8f7): undefined reference to `PyErr_Occurred'
_warnings.c:(.text+0x92c): undefined reference to `PyCallable_Check'
_warnings.c:(.text+0x93d): undefined reference to `PyExc_TypeError'
_warnings.c:(.text+0x94c): undefined reference to `PyErr_SetString'
_warnings.c:(.text+0x9bc): undefined reference to `PyObject_CallFunctionObjArgs'
_warnings.c:(.text+0xab0): undefined reference to `_Py_NoneStruct'
/tmp/_warnings-8f2147.o: In function `PyErr_WarnExplicit':
_warnings.c:(.text+0xd47): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0xd54): undefined reference to `PyUnicode_DecodeFSDefault'
_warnings.c:(.text+0xd96): undefined reference to `PyUnicode_FromString'
/tmp/_warnings-8f2147.o: In function `PyErr_WarnExplicitFormat':
_warnings.c:(.text+0x1041): undefined reference to `PyUnicode_DecodeFSDefault'
_warnings.c:(.text+0x1070): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x10bc): undefined reference to `PyUnicode_FromFormatV'
/tmp/_warnings-8f2147.o: In function `_PyWarnings_Init':
_warnings.c:(.text+0x12c8): undefined reference to `PyModule_Create2'
_warnings.c:(.text+0x1351): undefined reference to `PyModule_AddObject'
_warnings.c:(.text+0x137b): undefined reference to `PyDict_New'
_warnings.c:(.text+0x13d4): undefined reference to `PyModule_AddObject'
_warnings.c:(.text+0x1408): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x1461): undefined reference to `PyModule_AddObject'
/tmp/_warnings-8f2147.o: In function `init_filters':
_warnings.c:(.text+0x14ae): undefined reference to `PyList_New'
_warnings.c:(.text+0x14d9): undefined reference to `PyExc_DeprecationWarning'
_warnings.c:(.text+0x150e): undefined reference to `PyExc_PendingDeprecationWarning'
_warnings.c:(.text+0x1543): undefined reference to `PyExc_ImportWarning'
_warnings.c:(.text+0x1577): undefined reference to `Py_BytesWarningFlag'
_warnings.c:(.text+0x1598): undefined reference to `Py_BytesWarningFlag'
_warnings.c:(.text+0x15cd): undefined reference to `PyExc_BytesWarning'
_warnings.c:(.text+0x160a): undefined reference to `PyExc_ResourceWarning'
/tmp/_warnings-8f2147.o: In function `setup_context':
_warnings.c:(.text+0x1853): undefined reference to `_PyThreadState_Current'
_warnings.c:(.text+0x195c): undefined reference to `PyThreadState_Get'
_warnings.c:(.text+0x198c): undefined reference to `PyFrame_GetLineNumber'
_warnings.c:(.text+0x1a34): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x1a4e): undefined reference to `PyDict_New'
_warnings.c:(.text+0x1a89): undefined reference to `PyDict_SetItemString'
_warnings.c:(.text+0x1ac7): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x1aeb): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x1b31): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x1be9): undefined reference to `_PyUnicode_Ready'
_warnings.c:(.text+0x1c0f): undefined reference to `PyUnicode_GetLength'
_warnings.c:(.text+0x2028): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x2170): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x22b8): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x2400): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x24ef): undefined reference to `PyUnicode_Substring'
_warnings.c:(.text+0x253c): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x255f): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x2577): undefined reference to `_PySys_GetObjectId'
_warnings.c:(.text+0x25ba): undefined reference to `PyList_Size'
_warnings.c:(.text+0x25d4): undefined reference to `PyList_GetItem'
_warnings.c:(.text+0x25fb): undefined reference to `PyObject_IsTrue'
_warnings.c:(.text+0x26d5): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x270d): undefined reference to `PyUnicode_FromString'
/tmp/_warnings-8f2147.o: In function `normalize_module':
_warnings.c:(.text+0x2981): undefined reference to `PyUnicode_GetLength'
_warnings.c:(.text+0x29b7): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x2d5d): undefined reference to `PyUnicode_Substring'
/tmp/_warnings-8f2147.o: In function `already_warned':
_warnings.c:(.text+0x2dd9): undefined reference to `_PyDict_GetItemId'
_warnings.c:(.text+0x2df2): undefined reference to `PyLong_Type'
_warnings.c:(.text+0x2e09): undefined reference to `PyLong_AsLong'
_warnings.c:(.text+0x2e20): undefined reference to `PyDict_Clear'
_warnings.c:(.text+0x2e2d): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x2e5f): undefined reference to `_PyDict_SetItemId'
_warnings.c:(.text+0x2f0e): undefined reference to `PyDict_GetItem'
_warnings.c:(.text+0x2f26): undefined reference to `PyObject_IsTrue'
_warnings.c:(.text+0x2f60): undefined reference to `_Py_TrueStruct'
_warnings.c:(.text+0x2f69): undefined reference to `PyDict_SetItem'
/tmp/_warnings-8f2147.o: In function `get_filter':
_warnings.c:(.text+0x2fce): undefined reference to `PyErr_Occurred'
_warnings.c:(.text+0x3078): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x3087): undefined reference to `PyErr_SetString'
_warnings.c:(.text+0x30da): undefined reference to `PyTuple_Size'
_warnings.c:(.text+0x30ec): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x3101): undefined reference to `PyErr_Format'
_warnings.c:(.text+0x31b1): undefined reference to `PyObject_IsSubclass'
_warnings.c:(.text+0x31da): undefined reference to `PyLong_AsSsize_t'
_warnings.c:(.text+0x31f4): undefined reference to `PyErr_Occurred'
_warnings.c:(.text+0x329f): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x32ae): undefined reference to `PyErr_SetString'
/tmp/_warnings-8f2147.o: In function `get_once_registry':
_warnings.c:(.text+0x32f7): undefined reference to `PyErr_Occurred'
/tmp/_warnings-8f2147.o: In function `update_registry':
_warnings.c:(.text+0x33be): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x33f1): undefined reference to `PyTuple_Pack'
_warnings.c:(.text+0x340e): undefined reference to `PyTuple_Pack'
/tmp/_warnings-8f2147.o: In function `get_warnings_attr':
_warnings.c:(.text+0x3536): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x3564): undefined reference to `PyImport_GetModuleDict'
_warnings.c:(.text+0x3579): undefined reference to `PyDict_Contains'
_warnings.c:(.text+0x35ae): undefined reference to `PyDict_GetItem'
_warnings.c:(.text+0x35bf): undefined reference to `PyObject_HasAttrString'
_warnings.c:(.text+0x35e2): undefined reference to `PyObject_GetAttrString'
/tmp/_warnings-8f2147.o: In function `show_warning':
_warnings.c:(.text+0x363d): undefined reference to `PyOS_snprintf'
_warnings.c:(.text+0x3656): undefined reference to `_PyObject_GetAttrId'
_warnings.c:(.text+0x3679): undefined reference to `_PySys_GetObjectId'
_warnings.c:(.text+0x36b8): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x36d6): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x36f6): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x3717): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x3737): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x3758): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x3867): undefined reference to `_PyUnicode_Ready'
_warnings.c:(.text+0x3c5e): undefined reference to `PyUnicode_Substring'
_warnings.c:(.text+0x3c8a): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x3ceb): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x3d05): undefined reference to `_Py_DisplaySourceLine'
_warnings.c:(.text+0x3d8a): undefined reference to `PyErr_Clear'
/tmp/_warnings-8f2147.o: In function `check_matched':
_warnings.c:(.text+0x3db2): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x3def): undefined reference to `_PyObject_CallMethodId'
_warnings.c:(.text+0x3e13): undefined reference to `PyObject_IsTrue'
/tmp/_warnings-8f2147.o: In function `get_default_action':
_warnings.c:(.text+0x3e97): undefined reference to `PyErr_Occurred'
/tmp/_warnings-8f2147.o: In function `warnings_warn':
_warnings.c:(.text+0x3f83): undefined reference to `PyArg_ParseTupleAndKeywords'
/tmp/_warnings-8f2147.o: In function `warnings_warn_explicit':
_warnings.c:(.text+0x4072): undefined reference to `PyArg_ParseTupleAndKeywords'
_warnings.c:(.text+0x40a2): undefined reference to `_PyUnicode_FromId'
_warnings.c:(.text+0x40cc): undefined reference to `_PyUnicode_FromId'
_warnings.c:(.text+0x40fa): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x4111): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x4143): undefined reference to `_PyObject_HasAttrId'
_warnings.c:(.text+0x416c): undefined reference to `PyObject_CallMethodObjArgs'
_warnings.c:(.text+0x418e): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x41a7): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4213): undefined reference to `PyObject_CallMethodObjArgs'
_warnings.c:(.text+0x428c): undefined reference to `PyList_GetItem'
/tmp/_warnings-8f2147.o: In function `warnings_filters_mutated':
_warnings.c:(.text+0x4406): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4414): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x441a): undefined reference to `_Py_NoneStruct'
/tmp/_warnings-8f2147.o: In function `get_category':
_warnings.c:(.text+0x4448): undefined reference to `PyExc_Warning'
_warnings.c:(.text+0x444d): undefined reference to `PyObject_IsInstance'
_warnings.c:(.text+0x4495): undefined reference to `PyExc_UserWarning'
_warnings.c:(.text+0x44aa): undefined reference to `PyExc_Warning'
_warnings.c:(.text+0x44af): undefined reference to `PyObject_IsSubclass'
_warnings.c:(.text+0x44db): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x44ea): undefined reference to `PyErr_SetString'
/tmp/_warnings-8f2147.o: In function `create_filter':
_warnings.c:(.text+0x4559): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x45c8): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x4637): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x46a6): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x46ef): undefined reference to `Py_FatalError'
_warnings.c:(.text+0x4707): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x473a): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x474b): undefined reference to `PyTuple_Pack'
Error: the following clang command did not run successfully:
    /usr/bin/ld -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64
    -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crt1.o
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crti.o
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/crtbegin.o
    -L/usr/lib/gcc/x86_64-linux-gnu/7.5.0
    -L/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu
    -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu
    -L/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../..
    -L/opt/infer-linux64-v1.0.0/lib/infer/facebook-clang-plugins/clang/install/bin/../lib
    -L/lib -L/usr/lib /tmp/_warnings-8f2147.o -lgcc --as-needed -lgcc_s
    --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/crtend.o
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crtn.o

Capturing in make/cc mode...
Python/_warnings.o: In function `PyErr_Warn':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:841: multiple definition of `PyErr_Warn'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0x330): first defined here
Python/_warnings.o: In function `PyErr_WarnEx':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:824: multiple definition of `PyErr_WarnEx'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0x290): first defined here
Python/_warnings.o: In function `PyErr_WarnExplicit':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:866: multiple definition of `PyErr_WarnExplicit'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0xd20): first defined here
Python/_warnings.o: In function `PyErr_WarnExplicitFormat':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:895: multiple definition of `PyErr_WarnExplicitFormat'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0xf10): first defined here
Python/_warnings.o: In function `PyErr_WarnExplicitObject':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:850: multiple definition of `PyErr_WarnExplicitObject'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0x360): first defined here
Python/_warnings.o: In function `PyErr_WarnFormat':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:801: multiple definition of `PyErr_WarnFormat'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0x0): first defined here
Python/_warnings.o: In function `_PyWarnings_Init':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1066: multiple definition of `_PyWarnings_Init'
/tmp/_warnings-0dc537.o:_warnings.c:(.text+0x12b0): first defined here
/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/_warnings-0dc537.o: In function `PyErr_WarnFormat':
_warnings.c:(.text+0x155): undefined reference to `PyUnicode_FromFormatV'
/tmp/_warnings-0dc537.o: In function `warn_unicode':
_warnings.c:(.text+0x203): undefined reference to `PyExc_RuntimeWarning'
/tmp/_warnings-0dc537.o: In function `PyErr_WarnEx':
_warnings.c:(.text+0x2a9): undefined reference to `PyUnicode_FromString'
/tmp/_warnings-0dc537.o: In function `PyErr_WarnExplicitObject':
_warnings.c:(.text+0x38e): undefined reference to `PyExc_RuntimeWarning'
/tmp/_warnings-0dc537.o: In function `warn_explicit':
_warnings.c:(.text+0x488): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4a2): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4b0): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4b6): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4f3): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x509): undefined reference to `PyExc_TypeError'
_warnings.c:(.text+0x518): undefined reference to `PyErr_SetString'
_warnings.c:(.text+0x588): undefined reference to `PyExc_Warning'
_warnings.c:(.text+0x58d): undefined reference to `PyObject_IsInstance'
_warnings.c:(.text+0x5b2): undefined reference to `PyObject_Str'
_warnings.c:(.text+0x5f8): undefined reference to `PyObject_CallFunction'
_warnings.c:(.text+0x61a): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x646): undefined reference to `PyTuple_Pack'
_warnings.c:(.text+0x66b): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x6f3): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x709): undefined reference to `PyErr_SetObject'
_warnings.c:(.text+0x728): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x742): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x75e): undefined reference to `_Py_TrueStruct'
_warnings.c:(.text+0x767): undefined reference to `PyDict_SetItem'
_warnings.c:(.text+0x788): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x7a9): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x7c3): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x81d): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x837): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x873): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x884): undefined reference to `PyExc_RuntimeError'
_warnings.c:(.text+0x89d): undefined reference to `PyErr_Format'
_warnings.c:(.text+0x8f7): undefined reference to `PyErr_Occurred'
_warnings.c:(.text+0x92c): undefined reference to `PyCallable_Check'
_warnings.c:(.text+0x93d): undefined reference to `PyExc_TypeError'
_warnings.c:(.text+0x94c): undefined reference to `PyErr_SetString'
_warnings.c:(.text+0x9bc): undefined reference to `PyObject_CallFunctionObjArgs'
_warnings.c:(.text+0xab0): undefined reference to `_Py_NoneStruct'
/tmp/_warnings-0dc537.o: In function `PyErr_WarnExplicit':
_warnings.c:(.text+0xd47): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0xd54): undefined reference to `PyUnicode_DecodeFSDefault'
_warnings.c:(.text+0xd96): undefined reference to `PyUnicode_FromString'
/tmp/_warnings-0dc537.o: In function `PyErr_WarnExplicitFormat':
_warnings.c:(.text+0x1041): undefined reference to `PyUnicode_DecodeFSDefault'
_warnings.c:(.text+0x1070): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x10bc): undefined reference to `PyUnicode_FromFormatV'
/tmp/_warnings-0dc537.o: In function `_PyWarnings_Init':
_warnings.c:(.text+0x12c8): undefined reference to `PyModule_Create2'
_warnings.c:(.text+0x1351): undefined reference to `PyModule_AddObject'
_warnings.c:(.text+0x137b): undefined reference to `PyDict_New'
_warnings.c:(.text+0x13d4): undefined reference to `PyModule_AddObject'
_warnings.c:(.text+0x1408): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x1461): undefined reference to `PyModule_AddObject'
/tmp/_warnings-0dc537.o: In function `init_filters':
_warnings.c:(.text+0x14ae): undefined reference to `PyList_New'
_warnings.c:(.text+0x14d9): undefined reference to `PyExc_DeprecationWarning'
_warnings.c:(.text+0x150e): undefined reference to `PyExc_PendingDeprecationWarning'
_warnings.c:(.text+0x1543): undefined reference to `PyExc_ImportWarning'
_warnings.c:(.text+0x1577): undefined reference to `Py_BytesWarningFlag'
_warnings.c:(.text+0x1598): undefined reference to `Py_BytesWarningFlag'
_warnings.c:(.text+0x15cd): undefined reference to `PyExc_BytesWarning'
_warnings.c:(.text+0x160a): undefined reference to `PyExc_ResourceWarning'
/tmp/_warnings-0dc537.o: In function `setup_context':
_warnings.c:(.text+0x1853): undefined reference to `_PyThreadState_Current'
_warnings.c:(.text+0x195c): undefined reference to `PyThreadState_Get'
_warnings.c:(.text+0x198c): undefined reference to `PyFrame_GetLineNumber'
_warnings.c:(.text+0x1a34): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x1a4e): undefined reference to `PyDict_New'
_warnings.c:(.text+0x1a89): undefined reference to `PyDict_SetItemString'
_warnings.c:(.text+0x1ac7): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x1aeb): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x1b31): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x1be9): undefined reference to `_PyUnicode_Ready'
_warnings.c:(.text+0x1c0f): undefined reference to `PyUnicode_GetLength'
_warnings.c:(.text+0x2028): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x2170): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x22b8): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x2400): undefined reference to `_Py_ctype_tolower'
_warnings.c:(.text+0x24ef): undefined reference to `PyUnicode_Substring'
_warnings.c:(.text+0x253c): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x255f): undefined reference to `PyUnicode_CompareWithASCIIString'
_warnings.c:(.text+0x2577): undefined reference to `_PySys_GetObjectId'
_warnings.c:(.text+0x25ba): undefined reference to `PyList_Size'
_warnings.c:(.text+0x25d4): undefined reference to `PyList_GetItem'
_warnings.c:(.text+0x25fb): undefined reference to `PyObject_IsTrue'
_warnings.c:(.text+0x26d5): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x270d): undefined reference to `PyUnicode_FromString'
/tmp/_warnings-0dc537.o: In function `normalize_module':
_warnings.c:(.text+0x2981): undefined reference to `PyUnicode_GetLength'
_warnings.c:(.text+0x29b7): undefined reference to `PyUnicode_FromString'
_warnings.c:(.text+0x2d5d): undefined reference to `PyUnicode_Substring'
/tmp/_warnings-0dc537.o: In function `already_warned':
_warnings.c:(.text+0x2dd9): undefined reference to `_PyDict_GetItemId'
_warnings.c:(.text+0x2df2): undefined reference to `PyLong_Type'
_warnings.c:(.text+0x2e09): undefined reference to `PyLong_AsLong'
_warnings.c:(.text+0x2e20): undefined reference to `PyDict_Clear'
_warnings.c:(.text+0x2e2d): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x2e5f): undefined reference to `_PyDict_SetItemId'
_warnings.c:(.text+0x2f0e): undefined reference to `PyDict_GetItem'
_warnings.c:(.text+0x2f26): undefined reference to `PyObject_IsTrue'
_warnings.c:(.text+0x2f60): undefined reference to `_Py_TrueStruct'
_warnings.c:(.text+0x2f69): undefined reference to `PyDict_SetItem'
/tmp/_warnings-0dc537.o: In function `get_filter':
_warnings.c:(.text+0x2fce): undefined reference to `PyErr_Occurred'
_warnings.c:(.text+0x3078): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x3087): undefined reference to `PyErr_SetString'
_warnings.c:(.text+0x30da): undefined reference to `PyTuple_Size'
_warnings.c:(.text+0x30ec): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x3101): undefined reference to `PyErr_Format'
_warnings.c:(.text+0x31b1): undefined reference to `PyObject_IsSubclass'
_warnings.c:(.text+0x31da): undefined reference to `PyLong_AsSsize_t'
_warnings.c:(.text+0x31f4): undefined reference to `PyErr_Occurred'
_warnings.c:(.text+0x329f): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x32ae): undefined reference to `PyErr_SetString'
/tmp/_warnings-0dc537.o: In function `get_once_registry':
_warnings.c:(.text+0x32f7): undefined reference to `PyErr_Occurred'
/tmp/_warnings-0dc537.o: In function `update_registry':
_warnings.c:(.text+0x33be): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x33f1): undefined reference to `PyTuple_Pack'
_warnings.c:(.text+0x340e): undefined reference to `PyTuple_Pack'
/tmp/_warnings-0dc537.o: In function `get_warnings_attr':
_warnings.c:(.text+0x3536): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x3564): undefined reference to `PyImport_GetModuleDict'
_warnings.c:(.text+0x3579): undefined reference to `PyDict_Contains'
_warnings.c:(.text+0x35ae): undefined reference to `PyDict_GetItem'
_warnings.c:(.text+0x35bf): undefined reference to `PyObject_HasAttrString'
_warnings.c:(.text+0x35e2): undefined reference to `PyObject_GetAttrString'
/tmp/_warnings-0dc537.o: In function `show_warning':
_warnings.c:(.text+0x363d): undefined reference to `PyOS_snprintf'
_warnings.c:(.text+0x3656): undefined reference to `_PyObject_GetAttrId'
_warnings.c:(.text+0x3679): undefined reference to `_PySys_GetObjectId'
_warnings.c:(.text+0x36b8): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x36d6): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x36f6): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x3717): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x3737): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x3758): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x3867): undefined reference to `_PyUnicode_Ready'
_warnings.c:(.text+0x3c5e): undefined reference to `PyUnicode_Substring'
_warnings.c:(.text+0x3c8a): undefined reference to `PyFile_WriteObject'
_warnings.c:(.text+0x3ceb): undefined reference to `PyFile_WriteString'
_warnings.c:(.text+0x3d05): undefined reference to `_Py_DisplaySourceLine'
_warnings.c:(.text+0x3d8a): undefined reference to `PyErr_Clear'
/tmp/_warnings-0dc537.o: In function `check_matched':
_warnings.c:(.text+0x3db2): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x3def): undefined reference to `_PyObject_CallMethodId'
_warnings.c:(.text+0x3e13): undefined reference to `PyObject_IsTrue'
/tmp/_warnings-0dc537.o: In function `get_default_action':
_warnings.c:(.text+0x3e97): undefined reference to `PyErr_Occurred'
/tmp/_warnings-0dc537.o: In function `warnings_warn':
_warnings.c:(.text+0x3f83): undefined reference to `PyArg_ParseTupleAndKeywords'
/tmp/_warnings-0dc537.o: In function `warnings_warn_explicit':
_warnings.c:(.text+0x4072): undefined reference to `PyArg_ParseTupleAndKeywords'
_warnings.c:(.text+0x40a2): undefined reference to `_PyUnicode_FromId'
_warnings.c:(.text+0x40cc): undefined reference to `_PyUnicode_FromId'
_warnings.c:(.text+0x40fa): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x4111): undefined reference to `PyDict_GetItemString'
_warnings.c:(.text+0x4143): undefined reference to `_PyObject_HasAttrId'
_warnings.c:(.text+0x416c): undefined reference to `PyObject_CallMethodObjArgs'
_warnings.c:(.text+0x418e): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x41a7): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4213): undefined reference to `PyObject_CallMethodObjArgs'
_warnings.c:(.text+0x428c): undefined reference to `PyList_GetItem'
/tmp/_warnings-0dc537.o: In function `warnings_filters_mutated':
_warnings.c:(.text+0x4406): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x4414): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x441a): undefined reference to `_Py_NoneStruct'
/tmp/_warnings-0dc537.o: In function `get_category':
_warnings.c:(.text+0x4448): undefined reference to `PyExc_Warning'
_warnings.c:(.text+0x444d): undefined reference to `PyObject_IsInstance'
_warnings.c:(.text+0x4495): undefined reference to `PyExc_UserWarning'
_warnings.c:(.text+0x44aa): undefined reference to `PyExc_Warning'
_warnings.c:(.text+0x44af): undefined reference to `PyObject_IsSubclass'
_warnings.c:(.text+0x44db): undefined reference to `PyExc_ValueError'
_warnings.c:(.text+0x44ea): undefined reference to `PyErr_SetString'
/tmp/_warnings-0dc537.o: In function `create_filter':
_warnings.c:(.text+0x4559): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x45c8): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x4637): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x46a6): undefined reference to `PyUnicode_InternFromString'
_warnings.c:(.text+0x46ef): undefined reference to `Py_FatalError'
_warnings.c:(.text+0x4707): undefined reference to `PyLong_FromLong'
_warnings.c:(.text+0x473a): undefined reference to `_Py_NoneStruct'
_warnings.c:(.text+0x474b): undefined reference to `PyTuple_Pack'
Python/_warnings.o: In function `PyErr_WarnFormat':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:811: undefined reference to `PyUnicode_FromFormatV'
Python/_warnings.o: In function `warn_unicode':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:788: undefined reference to `PyExc_RuntimeWarning'
Python/_warnings.o: In function `PyErr_WarnEx':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:826: undefined reference to `PyUnicode_FromString'
Python/_warnings.o: In function `PyErr_WarnExplicitObject':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:853: undefined reference to `PyExc_RuntimeWarning'
Python/_warnings.o: In function `warn_explicit':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:352: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:361: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:361: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:361: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:363: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:364: undefined reference to `PyExc_TypeError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:364: undefined reference to `PyErr_SetString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:379: undefined reference to `PyExc_Warning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:379: undefined reference to `PyObject_IsInstance'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:384: undefined reference to `PyObject_Str'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:391: undefined reference to `PyObject_CallFunction'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:396: undefined reference to `PyLong_FromLong'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:401: undefined reference to `PyTuple_Pack'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:405: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:418: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:419: undefined reference to `PyErr_SetObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:426: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:427: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:428: undefined reference to `_Py_TrueStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:428: undefined reference to `PyDict_SetItem'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:430: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:432: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:433: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:441: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:443: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:446: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:447: undefined reference to `PyExc_RuntimeError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:447: undefined reference to `PyErr_Format'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:459: undefined reference to `PyErr_Occurred'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:466: undefined reference to `PyCallable_Check'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:467: undefined reference to `PyExc_TypeError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:467: undefined reference to `PyErr_SetString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:474: undefined reference to `PyObject_CallFunctionObjArgs'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:487: undefined reference to `_Py_NoneStruct'
Python/_warnings.o: In function `PyErr_WarnExplicit':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:867: undefined reference to `PyUnicode_FromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:868: undefined reference to `PyUnicode_DecodeFSDefault'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:875: undefined reference to `PyUnicode_FromString'
Python/_warnings.o: In function `PyErr_WarnExplicitFormat':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:898: undefined reference to `PyUnicode_DecodeFSDefault'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:905: undefined reference to `PyUnicode_FromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:915: undefined reference to `PyUnicode_FromFormatV'
Python/_warnings.o: In function `_PyWarnings_Init':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1069: undefined reference to `PyModule_Create2'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1079: undefined reference to `PyModule_AddObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1083: undefined reference to `PyDict_New'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1088: undefined reference to `PyModule_AddObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1092: undefined reference to `PyUnicode_FromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1097: undefined reference to `PyModule_AddObject'
Python/_warnings.o: In function `init_filters':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1011: undefined reference to `PyList_New'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1019: undefined reference to `PyExc_DeprecationWarning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1021: undefined reference to `PyExc_PendingDeprecationWarning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1023: undefined reference to `PyExc_ImportWarning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1025: undefined reference to `Py_BytesWarningFlag'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1027: undefined reference to `Py_BytesWarningFlag'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1031: undefined reference to `PyExc_BytesWarning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1039: undefined reference to `PyExc_ResourceWarning'
Python/_warnings.o: In function `setup_context':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:508: undefined reference to `_PyThreadState_Current'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:513: undefined reference to `PyThreadState_Get'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:518: undefined reference to `PyFrame_GetLineNumber'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:526: undefined reference to `PyDict_GetItemString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:530: undefined reference to `PyDict_New'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:534: undefined reference to `PyDict_SetItemString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:542: undefined reference to `PyDict_GetItemString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:544: undefined reference to `PyUnicode_FromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:552: undefined reference to `PyDict_GetItemString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:558: undefined reference to `_PyUnicode_Ready'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:561: undefined reference to `PyUnicode_GetLength'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:569: undefined reference to `_Py_ctype_tolower'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:570: undefined reference to `_Py_ctype_tolower'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:571: undefined reference to `_Py_ctype_tolower'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:572: undefined reference to `_Py_ctype_tolower'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:574: undefined reference to `PyUnicode_Substring'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:584: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:584: undefined reference to `PyUnicode_CompareWithASCIIString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:585: undefined reference to `_PySys_GetObjectId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:588: undefined reference to `PyList_Size'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:590: undefined reference to `PyList_GetItem'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:593: undefined reference to `PyObject_IsTrue'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:600: undefined reference to `PyUnicode_FromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:607: undefined reference to `PyUnicode_FromString'
Python/_warnings.o: In function `normalize_module':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:226: undefined reference to `PyUnicode_GetLength'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:231: undefined reference to `PyUnicode_FromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:242: undefined reference to `PyUnicode_Substring'
Python/_warnings.o: In function `already_warned':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:188: undefined reference to `_PyDict_GetItemId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:190: undefined reference to `PyLong_Type'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:191: undefined reference to `PyLong_AsLong'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:192: undefined reference to `PyDict_Clear'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:193: undefined reference to `PyLong_FromLong'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:196: undefined reference to `_PyDict_SetItemId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:203: undefined reference to `PyDict_GetItem'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:205: undefined reference to `PyObject_IsTrue'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:213: undefined reference to `_Py_TrueStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:213: undefined reference to `PyDict_SetItem'
Python/_warnings.o: In function `get_filter':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:115: undefined reference to `PyErr_Occurred'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:124: undefined reference to `PyExc_ValueError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:124: undefined reference to `PyErr_SetString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:136: undefined reference to `PyTuple_Size'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:137: undefined reference to `PyExc_ValueError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:137: undefined reference to `PyErr_Format'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:157: undefined reference to `PyObject_IsSubclass'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:161: undefined reference to `PyLong_AsSsize_t'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:162: undefined reference to `PyErr_Occurred'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:173: undefined reference to `PyExc_ValueError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:173: undefined reference to `PyErr_SetString'
Python/_warnings.o: In function `get_once_registry':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:75: undefined reference to `PyErr_Occurred'
Python/_warnings.o: In function `update_registry':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:259: undefined reference to `PyLong_FromLong'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:262: undefined reference to `PyTuple_Pack'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:265: undefined reference to `PyTuple_Pack'
Python/_warnings.o: In function `get_warnings_attr':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:51: undefined reference to `PyUnicode_InternFromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:56: undefined reference to `PyImport_GetModuleDict'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:57: undefined reference to `PyDict_Contains'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:61: undefined reference to `PyDict_GetItem'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:62: undefined reference to `PyObject_HasAttrString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:64: undefined reference to `PyObject_GetAttrString'
Python/_warnings.o: In function `show_warning':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:282: undefined reference to `PyOS_snprintf'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:284: undefined reference to `_PyObject_GetAttrId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:288: undefined reference to `_PySys_GetObjectId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:295: undefined reference to `PyFile_WriteObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:297: undefined reference to `PyFile_WriteString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:299: undefined reference to `PyFile_WriteObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:301: undefined reference to `PyFile_WriteString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:303: undefined reference to `PyFile_WriteObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:305: undefined reference to `PyFile_WriteString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:317: undefined reference to `_PyUnicode_Ready'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:329: undefined reference to `PyUnicode_Substring'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:333: undefined reference to `PyFile_WriteObject'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:335: undefined reference to `PyFile_WriteString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:338: undefined reference to `_Py_DisplaySourceLine'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:343: undefined reference to `PyErr_Clear'
Python/_warnings.o: In function `check_matched':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:27: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:29: undefined reference to `_PyObject_CallMethodId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:33: undefined reference to `PyObject_IsTrue'
Python/_warnings.o: In function `get_default_action':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:92: undefined reference to `PyErr_Occurred'
Python/_warnings.o: In function `warnings_warn':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:680: undefined reference to `PyArg_ParseTupleAndKeywords'
Python/_warnings.o: In function `warnings_warn_explicit':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:703: undefined reference to `PyArg_ParseTupleAndKeywords'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:719: undefined reference to `_PyUnicode_FromId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:721: undefined reference to `_PyUnicode_FromId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:725: undefined reference to `PyDict_GetItemString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:726: undefined reference to `PyDict_GetItemString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:732: undefined reference to `_PyObject_HasAttrId'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:735: undefined reference to `PyObject_CallMethodObjArgs'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:739: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:740: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:745: undefined reference to `PyObject_CallMethodObjArgs'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:753: undefined reference to `PyList_GetItem'
Python/_warnings.o: In function `warnings_filters_mutated':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:775: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:775: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:775: undefined reference to `_Py_NoneStruct'
Python/_warnings.o: In function `get_category':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:634: undefined reference to `PyExc_Warning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:634: undefined reference to `PyObject_IsInstance'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:641: undefined reference to `PyExc_UserWarning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:644: undefined reference to `PyExc_Warning'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:644: undefined reference to `PyObject_IsSubclass'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:648: undefined reference to `PyExc_ValueError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:648: undefined reference to `PyErr_SetString'
Python/_warnings.o: In function `create_filter':
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:965: undefined reference to `PyUnicode_InternFromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:973: undefined reference to `PyUnicode_InternFromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:981: undefined reference to `PyUnicode_InternFromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:989: undefined reference to `PyUnicode_InternFromString'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:996: undefined reference to `Py_FatalError'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1000: undefined reference to `PyLong_FromLong'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1003: undefined reference to `_Py_NoneStruct'
/home/cs18/inferDoc/Python-3.4.3rc1/Python/_warnings.c:1003: undefined reference to `PyTuple_Pack'
Error: the following clang command did not run successfully:
    /usr/bin/ld -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64
    -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crt1.o
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crti.o
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/crtbegin.o
    -L/usr/lib/gcc/x86_64-linux-gnu/7.5.0
    -L/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu
    -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu
    -L/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../..
    -L/opt/infer-linux64-v1.0.0/lib/infer/facebook-clang-plugins/clang/install/bin/../lib
    -L/lib -L/usr/lib /tmp/_warnings-0dc537.o Python/_warnings.o -lgcc
    --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s
    --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/7.5.0/crtend.o
    /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../x86_64-linux-gnu/crtn.o

